inherit_from: ../base/.rubocop.yml

inherit_mode:
  override:
    - AllowedNames

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - c
    - d

Naming/UncommunicativeBlockParamName:
  inherit_mode:
    merge:
      - AllowedNames
  AllowedNames:
    - i
    - j
